name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ main ]

env:
  NODE_ENV: production
  PORT: 9000

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Run Build
      run: npm run build
      if: success()

    - name: Setup SSH
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy-key
        chmod 600 ~/.ssh/deploy-key
        ssh-keyscan -H 13.232.193.173 >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      env:
        DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: 13.232.193.173
        USERNAME: ubuntu
        PM2_APP_NAME: your-app-name
      run: |
        ssh -i ~/.ssh/deploy-key ubuntu@13.232.193.173 '
          cd /var/www/your-app-name && \
          git pull origin main && \
          npm ci --production && \
          npm run build && \
          pm2 reload ecosystem.config.js --env production || \
          pm2 start ecosystem.config.js --env production'

    - name: Health Check
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        sleep 10
        curl --fail http://13.232.193.173:9000/health || exit 1
