name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ main ]

env:
  NODE_ENV: production
  PORT: 9000

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Build
        run: npm run build
        if: success()

      - name: Setup SSH
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy-key
          chmod 600 ~/.ssh/deploy-key
          ssh-keyscan -H 13.232.193.173 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: 13.232.193.173
          USERNAME: ubuntu
          PM2_APP_NAME: your-app-name
        run: |
          ssh -i ~/.ssh/deploy-key ubuntu@13.232.193.173 '
            # Ensure NVM is loaded and node/npm are available
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # Loads nvm
            
            # Clone the repository if the directory doesn't exist
            if [ ! -d /var/www/your-app-name ]; then
              sudo git clone https://github.com/ShubhamAXS19/simple-node-ts.git /var/www/your-app-name;
            fi

            # Change to the app directory and pull the latest changes
            cd /var/www/your-app-name && \
            sudo git pull origin main && \
            
            # Install npm dependencies
            sudo npm ci --production && \
            
            # Build the project
            sudo npm run build && \
            
            # Install pm2 globally if not already installed
            if ! command -v pm2 > /dev/null; then
              sudo npm install -g pm2;
            fi
            
            # Reload or start the app using pm2
            pm2 reload ecosystem.config.js --env production || \
            pm2 start ecosystem.config.js --env production'

      - name: Health Check
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          sleep 10
          curl --fail http://13.232.193.173:9000/health || exit 1
